### ISSUE TITLE
Tables count error in Rust example (bad wasm?)

### ISSUE THREAD

**Issue by jkriss** [bytecodealliance/wasmtime-demos#13]
When running the Rust example, I get the following error:

```
$ cargo run
   Compiling markdown v0.1.0 (/Users/jkriss/Desktop/wasmtime-demos/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 4.26s
     Running `target/debug/markdown`
Error: tables count must be at most 1 (at offset 405)
```

This is after cloning the repo, installing Rust nightly and wasm-pack, then:

```
cd markdown
export WASM_INTERFACE_TYPES=1
wasm-pack build
cd ../rust
cp ../markdown/pkg/markdown.wasm .
```

In the python example, I get:
```
$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import markdown
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/wasmtime/__init__.py", line 46, in exec_module
    res = instantiate(data, imports)
Exception: Validation error: module did not validate
```

It seems that something's going wrong with the initial wasm generation. Any ideas? This is with 1.42.0-nightly and wasm-pack 0.8.1.

**Comment by alexcrichton** [comment]
Thanks for the report! For now you should be able to get examples working using 0.2.55 of wasm-bindgen. The 0.2.56 version and later emit a version of the interface types format that wasmtime doesn't support yet, but I'm working on it!

**Comment by peterhuene** [comment]
I think we should fix the markdown demo to be `=0.2.55` until Wasmtime and the demos catch up to these changes.

**Comment by alexcrichton** [comment]
👍 Sounds like a good plan to me!

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!
