### ISSUE TITLE
No module named '__wbindgen_placeholder__'

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmtime-demos#2]
On a Linux host, following the instructions for the Python demo, I get the following errors:
```
$ cd markdown
$ cargo build --target wasm32-unknown-unknown
$ cp target/wasm32-unknown-unknown/debug/markdown.wasm ../python
$ cd ../python
$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import markdown
  File "[...]/.local/lib/python3.6/site-packages/wasmtime/__init__.py", line 42, in exec_module
    imported_module = import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '__wbindgen_placeholder__'
$ wasm2wat markdown.wasm |grep 'import.*wbindgen'
  (import "__wbindgen_placeholder__" "__wbindgen_describe" (func $__wbindgen_describe (type 0)))
  (import "__wbindgen_placeholder__" "__wbindgen_throw" (func $__wbindgen_throw (type 4)))
  (import "__wbindgen_anyref_xform__" "__wbindgen_anyref_table_grow" (func $__wbindgen_anyref_table_grow (type 6)))
  (import "__wbindgen_anyref_xform__" "__wbindgen_anyref_table_set_null" (func $__wbindgen_anyref_table_set_null (type 0)))
```

**Comment by sunfishcode** [comment]
Steps needed to run the demo which are not mentioned in the README.md:
 - export WASM_INTERFACE_TYPES=1
 - wasm-pack build (instead of cargo build)
 - copy output from pkg/markdown.wasm (instead of target/wasm32-unknown-unknown/debug/markdown.wasm)

**Comment by OrangeTux** [comment]
I have the same problem. I figured out that the file `target/wasm32-unknown-unknown/debug/markdown.wasm` is broken. It will also fail to run if you feed it to `wasmtime`. I'm using wasmtime v0.7.0.

``` shell
$ wasmtime target/wasm32-unknown-unknown/release/markdown.wasm
Error: failed to process main module `target/wasm32-unknown-unknown/release/markdown.wasm`

Caused by:
    Import module __wbindgen_placeholder__ was not found
```

**EDIT** I realize that I used the wasm file in `target/`. If I use the wasm file from `pkg/` I get a different error. This is the same error as #13 

``` bash
$ wasmtime pkg/markdown.wasm
Error: failed to process main module `pkg/markdown.wasm`

Caused by:
    func type returns multiple values (at offset 47)
```

**Comment by OrangeTux** [comment]
Thanks to @ereslibre and  [Gitter](https://gitter.im/CraneStation/Lobby) I could get rid of this bug. See [these chats](https://gitter.im/CraneStation/Lobby?at=5e0f6805316c1473270cae38).

The problem is that the current version of wasmtime has disabled support for multiple return values. Luckily you can enable this feature by modifying the wasmtime's source code and recompile it. 

[Here is a link](ebf67271e1f670b04f9797121d3ed3eb) to a diff that patches wasmtime so you can enable support for multiple return values using a command line flag.

Patching wasmtime and enable support for multiple return values fixed this problem for me. Unfortunately I faced a new problem:

``` bash
$ wasmtime --enable-multivalue --invoke greet ./target/wasm32-wasi/release/hello_world.wasm "wasmtime CLI"
Error: failed to process main module `./target/wasm32-wasi/release/hello_world.wasm`

Caused by:
    tables count must be at most 1 (at offset 420)
```

#13 tracks this issue.

**Comment by ereslibre** [comment]
Thank you @OrangeTux! Happy it helped you. BTW, the link to the patch for `wasmtime` CLI on your comment seems broken, here it is: https://gist.github.com/ereslibre/ebf67271e1f670b04f9797121d3ed3eb.

Edit: just updated the patch at https://gist.github.com/ereslibre/ebf67271e1f670b04f9797121d3ed3eb to build with latest `master` (https://github.com/bytecodealliance/wasmtime/commit/787f50e107bbd434e9f28d413ec39ebb14fb88d5 did hide `features`).

**Comment by tomasol** [comment]
@ereslibre wasmtime.rs was refactored again. Is there an issue for this in [bytecodealliance/wasmtime](https://github.com/bytecodealliance/wasmtime/) ?

**Comment by ereslibre** [comment]
@tomasol, I didn't create any issue, it was mentioned on Gitter that the multi value feature would be exposed by the `wasmtime` CLI eventually. I'll check again this weekend; things are going fast on these projects :)

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!
