### ISSUE TITLE
Getting an error when I tried the dotnet demo on .net core 3.1

### ISSUE THREAD

**Issue by ajbennet** [bytecodealliance/wasmtime-demos#21]
I followed all the steps in the tutorial, but I couldnt get it to run. Below is the error.

c:\wasmtime-demos\dotnet>dotnet run
Unhandled exception. Wasmtime.WasmtimeException: Failed to bind function import 'wasi_snapshot_preview1.fd_write': the host does not contain a method with a matching 'Import' attribute.
   at Wasmtime.Bindings.Binding.BindFunction(FunctionImport import, IEnumerable`1 methods)
   at Wasmtime.Bindings.Binding.GetImportBindings(IHost host, Module module)
   at Wasmtime.IHost.GetImportBindings(Module module)
   at Wasmtime.Instance..ctor(Module module, IHost host)
   at Wasmtime.Module.Instantiate(IHost host)
   at WasmtimeDemo.Program.Main() in C:\Users\abbennet\workspace\wasi\wasmtime-demos\dotnet\Program.cs:line 20

**Comment by ajbennet** [comment]
Any updates on this? I m still facing this problem.

**Comment by tschneidereit** [comment]
CC @peterhuene, who'll have the most insights here.

**Comment by peterhuene** [comment]
Unfortunately the demo and the implementation have drifted significantly.

@tschneidereit @alexcrichton what do we think about retiring this repo in favor of essentially copying the demo as a walkthrough into each `wasmtime-<lang>` repo?  That way the demo scenario could be considered an additional test case that could be tested in CI nearest the implementation.

**Comment by peterhuene** [comment]
@ajbennet thanks for reporting this to us!  I'll see about updating the demo to work with the latest versions of Wasmtime and I'll let you know when it is fixed.

**Comment by tschneidereit** [comment]
> what do we think about retiring this repo in favor of essentially copying the demo as a walkthrough into each `wasmtime-<lang>` repo?

I think that makes a lot of sense!

**Comment by alexcrichton** [comment]
👍 

Sounds reasonable to me!

**Comment by ajbennet** [comment]
Thanks @peterhuene. Is there another link or sample that you can point me to, to try out wasmtime and explore it?

**Comment by peterhuene** [comment]
@ajbennet there isn't one, at least for .NET, that really utilizes WASI since full support for using the WASI implementation directly from Wasmtime was implemented a few months after this demo was created.

Even this markdown demo barely uses WASI since the stub implementation (which will no longer be required when I update the demo) doesn't actually do anything.

I'll see if I can come up with more samples in the [Wasmtime for .NET](https://github.com/bytecodealliance/wasmtime-dotnet) that show off WASI too.

**Comment by ajbennet** [comment]
Thanks @peterhuene , I appreciate it. I am still new to WASI and trying to wrap my head around it, so forgive me if this is a dumb question. I was wondering if it makes sense to create cross platform client UI applications using WASI and WASM as the payload. So it runs in the browser and any machine regardless of the architecture etc. ? Has there been any efforts in that front?

**Comment by peterhuene** [comment]
Not a dumb question at all!

You could definitely emulate the Electron model with WASI and WebAssembly where a platform-specific native host abstracts away the UI interactions via imported functions and the remainder (i.e. the "application") is implemented in WebAssembly.  Unlike Electron, though, you wouldn't be required to have a JavaScript engine to load the WebAssembly ([Electron can do this now via V8's support for loading WebAssembly](https://github.com/anderejd/electron-wasm-rust-example)) but instead you could directly use a WebAssembly engine like Wasmtime.

One day there might even be a GUI module for WASI such that "GUI" WebAssembly applications would work in environments that provide such a WASI module, much like how a .NET application that references WinRT/WPF/Winforms works, but theoretically in a cross-platform way.

I personally don't know of any real efforts in this space as a lot of the focus has been more in the backend server space (i.e. disrupting the world of networked containers), but that doesn't mean there aren't any!

**Comment by ajbennet** [comment]
Thanks Peter, this is great. Appreciate your response. I ll keep exploring.

_Abi

________________________________

**Comment by alexcrichton** [comment]
I'm going to close out this issue in preparation for achiving this repository.
