### ISSUE TITLE
Two errors when trying to run the Python demo

### ISSUE THREAD

**Issue by Keithcat1** [bytecodealliance/wasmtime-demos#24]
C:\py\git>git clone https://github.com/bytecodealliance/wasmtime-demos
Cloning into 'wasmtime-demos'...
remote: Enumerating objects: 127, done.
Receiving objects: 100% (127/127), 29.73 KiB | 2.48 MiB/s, done.
Resolving deltas: 100% (38/38), done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 127 (delta 12), reused 10 (delta 10), pack-reused 112

C:\py\git>cd wasmtime-demos

C:\py\git\wasmtime-demos>cd markdown

C:\py\git\wasmtime-demos\markdown>cargo build --target=wasm32-unknown-unknown
    Updating crates.io index
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling log v0.4.14
   Compiling wasm-bindgen-shared v0.2.55
   Compiling syn v1.0.80
   Compiling cfg-if v1.0.0
   Compiling bumpalo v2.6.0
   Compiling version_check v0.9.3
   Compiling lazy_static v1.4.0
   Compiling memchr v2.4.1
   Compiling pulldown-cmark v0.5.3
   Compiling wasm-bindgen v0.2.55
   Compiling bitflags v1.3.2
   Compiling cfg-if v0.1.10
   Compiling unicase v2.6.0
   Compiling quote v1.0.10
   Compiling wasm-bindgen-backend v0.2.55
   Compiling wasm-bindgen-macro-support v0.2.55
   Compiling wasm-bindgen-macro v0.2.55
   Compiling markdown v0.1.0 (C:\py\git\wasmtime-demos\markdown)
    Finished dev [unoptimized + debuginfo] target(s) in 30.04s

C:\py\git\wasmtime-demos\markdown>
C:\py\git\wasmtime-demos\markdown>cd ..

C:\py\git\wasmtime-demos>cd python

C:\py\git\wasmtime-demos\python>copy ..\markdown\target\wasm32-unknown-unknown\debug\markdown.wasm
        1 file(s) copied.

C:\py\git\wasmtime-demos\python>python run.py
Traceback (most recent call last):
  File "C:\py\git\wasmtime-demos\python\run.py", line 7, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'

C:\py\git\wasmtime-demos\python>python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wasmtime.loader
>>> import markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\lib\site-packages\wasmtime\loader.py", line 72, in exec_module
    imported_module = importlib.import_module(module_name)
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '__wbindgen_placeholder__'
>>>

**Comment by alexcrichton** [comment]
I'm going to close out this issue in preparation for archiving this repository. Sorry for not otherwise getting around to helping out out (2 years ago!), but time flies!
