### ISSUE TITLE
archive and mark this repository read-only

### ISSUE THREAD

**Issue by ubiquitous-dev** [bytecodealliance/wasmtime-demos#26]
The README states that this repository is no longer in use / maintained, due to examples being included in the upstream repository bytecodealiance / wasmtime.  I think this is a good change, so that the demos can evolve with the runtime.  

However, the way this repository is set up is not clear - there are still issues being created here.  The standard on GitHub is to put a big banner at the top of the README with a redirect to the new repository, and marking the repository read-only.

**Comment by alexcrichton** [comment]
Good idea! I'll work on getting this done. I'm going to close this in the meantime to close out issues before archiving.
