### ISSUE TITLE
Exception: version mismatch in the bindings section

### ISSUE THREAD

**Issue by whb07** [bytecodealliance/wasmtime-demos#3]
Running strictly from the example it looks like something in the instantiate function within wasmtime broke.

```bash
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import markdown
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/private/tmp/wasmtime-demos/python/venv/lib/python3.7/site-packages/wasmtime/__init__.py", line 46, in exec_module
    res = instantiate(data, imports)
Exception: version mismatch in the bindings section: wasm file has `0.5.0` and this library supports `0.4.0`
```

**Comment by jmfrank63** [comment]
@whb07 Ran into the same issue. @tschneidereit did not publish any source code but you can find it at https://wasmtime.dev/. Clone the source and inside the `misc/wasmtime-py` directory you'll find instructions how to build the python `wasmtime` module.
Once build you can simply overwrite the `.so` file in your local installation or add the `build/lib/` directory to your `PYTHONPATH`. Hih.

**Comment by zababurinsv** [comment]
I  created
lib_wasmtime.cpython-37m-x86_64-linux-gnu.so 
How i can add this file in PYTHONPATH ? or where find *.so for overwriting ?

**Comment by jmfrank63** [comment]
@zababurinsv It is in your `site-packages/wasmtime` directory. Which site-packages depends on your platform and if you installed wasmtime as system or user package.
To add it to your PYTHONPATH add the path of the file to an environment variable called `PYTHONPATH`.

**Comment by vladikoff** [comment]
Did anyone have luck with the js examples https://github.com/bytecodealliance/wasmtime-demos/issues/7 ?

**Comment by alexcrichton** [comment]
I'm going to now that we've [temporarily removed interface types support](https://github.com/bytecodealliance/wasmtime/pull/1292), but stay tuned to https://github.com/bytecodealliance/wasmtime/issues/677 for future updates!
