### ISSUE TITLE
webpack and node.js demos fail with a version mismatch

### ISSUE THREAD

**Issue by vladikoff** [bytecodealliance/wasmtime-demos#7]
> ERROR in ./markdown.wasm
Module build failed (from ./node_modules/wasm-interface-types-loader/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) ErrorMessage { msg: "version mismatch in the bindings section: wasm file has `0.6.0` and this library supports `0.4.0`" }

**Comment by tschneidereit** [comment]
This should be addressed by #9. Sorry for the breakage!
