### ISSUE TITLE
 version mismatch in the bindings section: wasm file has `0.5.0` and this library supports `0.6.0`

### ISSUE THREAD

**Issue by zababurinsv** [bytecodealliance/wasmtime-demos#8]
Hi.
I want to build wasm file in project, and when i run this file i getting this error.

version mismatch in the bindings section: wasm file has `0.5.0` and this library supports `0.6.0`

How can i fix this ?
And where can i see this versions ?

**Comment by tschneidereit** [comment]
This should be addressed by #9. Sorry for the breakage!
